language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

script:
  ./gradlew build test

jdk:
  - oraclejdk8

sudo: false

before_install:
  - yes | sdkmanager "platforms;android-27"

cache:
  directories:
    - $HOME/.m2
