language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25

script:
  ./gradlew build test

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2
